In [2]:
from transformers import AutoModel, AutoTokenizer
import torch
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [3]:
MODEL_NAME = 'sentence-transformers/all-mpnet-base-v2'
#MODEL_NAME = 'sentence-transformers/all-MiniLM-L6-v2'

In [4]:
sentences = ['NLP is about','What is NLP?',      
             'NLP is good', 'the album is fire']

In [5]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME,
                                  output_hidden_states = True 
                                  )
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')
with torch.no_grad():  
    model_output = model(**encoded_input)

In [6]:
encoded_input['input_ids']

tensor([[    0, 17957,  2365,  2007,  2059,     2,     1],
        [    0,  2058,  2007, 17957,  2365,  1033,     2],
        [    0, 17957,  2365,  2007,  2208,     2,     1],
        [    0,  2000,  2205,  2007,  2547,     2,     1]])

In [11]:
nlp1 = (model_output['last_hidden_state'][0][1]+ model_output['last_hidden_state'][0][2])/2 # NLP is "NLP is about"
nlp2 = (model_output['last_hidden_state'][1][3]+ model_output['last_hidden_state'][1][4])/2 # NLP is "what is NLP?"
cosine_similarity([np.array(nlp1)], [np.array(nlp2)])

array([[0.82143974]], dtype=float32)

In [19]:
nlp1 = (model_output['last_hidden_state'][0][1]+ model_output['last_hidden_state'][0][2])/2 # NLP in "NLP is about"
is1 = model_output['last_hidden_state'][0][3]                                               # is  in "NLP is about"
cosine_similarity([np.array(nlp1)], [np.array(is1)])

array([[0.81763816]], dtype=float32)

In [22]:
is3 = model_output['last_hidden_state'][2][3] # "is" in NLP is good
is4 = model_output['last_hidden_state'][3][3] # "is" in the album is fire
cosine_similarity([np.array(is3)], [np.array(is4)])

array([[0.14208727]], dtype=float32)